spring:
  profiles: default
  application:
    name: TIPOSVIA-CLIENT
  datasource:
    url: jdbc:mysql://localhost:3305/tiposvia?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: POIzxc01
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8098
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
    register-with-eureka: true


