
server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/

zuul:
  ignored-services: '*'
  routes:
    tipovia-services:
      path: /tv/**
      serviceId: tiposvia-client
      stripPrefix: true
spring:
  application:
    name: zuul-api-gateway-server
