spring:
  profiles: default
  application:
    name: VIA-CLIENT
  datasource:
    url: jdbc:sqlserver://localhost;database=via
    username: sa
    password: POIzxc01!
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
server:
  port: 8076
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
    register-with-eureka: true
