spring:
  profiles: default
  application:
    name: MANTENIMIENTO-CLIENT
  datasource:
    url: jdbc:sqlserver://localhost;database=mantenimiento
    username: sa
    password: POIzxc01!
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
server:
  port: 8094
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
    healthcheck:
      enabled: true
      lease:
        duration: 5


