server:
  port: 8010

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: api-gateway


logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG
